### PR TITLE
Fix small Bpm parser issue 

### PR DESCRIPTION
**Pull request by nikolaikarner**
fix: When calculate data Length in BmpParser returns 0 it then thinks it is also a  TLV container. Fixed by adding else to if.

### CODE REVIEW

**Comment by tinohager** [comment]
i think we need only remove `byte[] bmpData;` and add the `var` -> `var bmpData = data.Slice(currentPosition, dataLength).ToArray();`

**Comment by nikolaikarner** [comment]
I do not exactly understand how that would solve the issue maby I dont understand where you want to add it. I had the problem that in my message there is a section "22F0F0" and this leads to the result of CalculateDatatLength 0 which is correct. But the it assigns the 0 to dataLenth which the leads to accessing the block where the TLV container is read altough it is not a TLV container.

**Comment by tinohager** [comment]
Can they perhaps provide more information about this problem? What kind of command was called?

**Comment by nikolaikarner** [comment]
I tried to parse a Status Information response with the StatusInformationParser backtracked the problem to this section of the code. 
The message is:
040F44276C040000000012004909780C1133390D0817**22F0F0**0B000000196029525002958BF0F100 with then a tlv container but the problem happens with the bold section

**Comment by tinohager** [comment]
I will be looking at the Issue in the next few days. Can you give me some information about the terminal and the payment provider so that we know where these problems occur?

**Comment by nikolaikarner** [comment]
The terminal Feig Electronics cvend box+ and the payment provider is lavego.

**Comment by tinohager** [comment]
@nikolaikarner The new version is now available, thanks

**Pull request merged**
